name: cs7643-finalproject
channels:
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - ipykernel
  - pip:
    - torch
    - torchtext
    - torchaudio
    - notebook
    - numpy
    - spacy
    - Resemblyzer
    - audio-separator[cpu]
    - datasets